### ISSUE TITLE
graph.HammingDistance

### ISSUE THREAD

**Issue by yuan6d9b** [fguzman82/CLIP-Finder2#3]
How to find all photos from the photo library whose hamming distance < threshold of a given photo, using graph.HammingDistance

**Comment by fguzman82** [comment]
# Finding Similar Photos Using Hamming Distance

## Question

How to find all photos from the photo library whose Hamming distance < threshold of a given photo, using `graph.HammingDistance`?

## Answer

Thank you for your question about finding photos with a Hamming distance below a threshold. While CLIP-Finder currently uses cosine similarity for image comparison, we can adapt the approach to use Hamming distance. Here's how you could implement this using the Metal Performance Shaders Graph API:

1. First, ensure your image embeddings are binary (or can be converted to binary). CLIP embeddings are typically floating-point, so you might need to binarize them first.

2. Use `MPSGraphHammingDistance` to compute the Hamming distance between your reference image and all other images in the library.

3. Use `MPSGraphLessThan` to create a mask of images below the threshold.

### Code Example

Here's a code example of how this could be implemented:

```swift
func findSimilarPhotos(referencePhotoID: String, threshold: Float) -> [String] {
    guard let device = MTLCreateSystemDefaultDevice(),
          let referenceVector = cachedPhotoVectors[referencePhotoID] else {
        return []
    }

    let graph = MPSGraph()
    
    // Convert MLMultiArray to MPSNDArray (assuming binary data)
    let referenceArray = MPSGraphExtensions.convertToMPSNDArray(mlMultiArray: referenceVector, device: device)
    
    // Prepare all photo vectors
    let photoVectors = Array(cachedPhotoVectors.values)
    let photoIDs = Array(cachedPhotoVectors.keys)
    let allPhotosArray = MPSGraphExtensions.convertToMPSNDArray(mlMultiArrays: photoVectors, device: device)
    
    // Create placeholders
    let referenceTensor = graph.placeholder(shape: referenceArray.shape, dataType: .uInt8, name: "reference")
    let allPhotosTensor = graph.placeholder(shape: allPhotosArray.shape, dataType: .uInt8, name: "all_photos")
    
    // Compute Hamming distances
    let distances = graph.hammingDistance(referenceTensor, allPhotosTensor, name: nil)
    
    // Create mask for distances below threshold
    let thresholdTensor = graph.constant(Float(threshold), shape: [1], dataType: .float32)
    let mask = graph.lessThan(distances, thresholdTensor, name: nil)
    
    // Run the graph
    let results = graph.run(feeds: [referenceTensor: MPSGraphTensorData(referenceArray),
                                    allPhotosTensor: MPSGraphTensorData(allPhotosArray)],
                            targetTensors: [mask])
    
    // Process results
    guard let maskArray = results[mask]?.mpsndarray() else { return [] }
    var boolArray = [Bool](repeating: false, count: photoIDs.count)
    maskArray.readBytes(&boolArray, strideBytes: nil)
    
    // Return IDs of similar photos
    return zip(photoIDs, boolArray).compactMap { $1 ? $0 : nil }
}
```
## Usage
### To use this function:

```swift
let similarPhotoIDs = findSimilarPhotos(referencePhotoID: "photo123", threshold: 10)
```

This will return an array of photo IDs that have a Hamming distance less than 10 from the reference photo.

### Notes:

This approach assumes binary embeddings. If your embeddings are floating-point, you'll need to binarize them first.
You might need to adjust the MPSGraphExtensions methods to correctly handle your data format.
Remember that Hamming distance is typically used with binary data, so ensure your embeddings are in an appropriate format before using this method.
